apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: argocd-agent
placementBindingDefaults:
  name: argocd-agent
policyDefaults:
  namespace: acm-policies
  remediationAction: enforce
policies:
  - name: argocd-agent
    description: Argo CD Agent
    hubTemplateOptions:
      serviceAccountName: argocd-agent-policy
    manifests:
      - path: manifests/base/
    placement:
      placementName: argocd-agent
