apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd-agent

resources:
- github.com/gnunn-gitops/cluster-config-v2/apps/openshift-gitops/overlays/argocd-agent
- argocd-agent-ca.yaml
- argocd-agent-client-tls.yaml
