apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: noobaa

resources:
- ../../base

patches:
  - patch: |
      - op: add
        path: /spec/pvPoolDefaultStorageClass
        value: nfs-csi
      - op: add
        path: /spec/disableLoadBalancerService
        value: true
      - op: add
        path: /spec/disableRoutes
        value: false
    target:
      kind: NooBaa
