apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: declarative-configurations
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster
  target:
    name: declarative-configurations
    creationPolicy: Owner
    template:
      data:
        keycloak-auth.yaml: |
          name: keycloak
          minimumRole: None
          uiEndpoint: central-stackrox.central-rhacs-operator.apps.hub.ocplab.com:443
          oidc:
              issuer: https://sso.ocplab.com/realms/ocplab
              mode: auto
              clientID: acs
              clientSecret: {{ .keycloak_client_secret }}
              disableOfflineAccessScope: true
          groups:
              - key: email
                value: admin@ocplab.com
                role: Admin
              - key: email
                value: gnunn+admin@redhat.com
                role: Admin
              - key: group
                value: cluster-admins
                role: Admin
        namespace-admin-permission-set.yaml: |
          name: Namespace Administrator
          description: A user that is an administrator of one or namespaces across various clusters
          resources:
            - resource: Access
              access: NO_ACCESS
            - resource: Administration
              access: NO_ACCESS
            - resource: Alert
              access: READ_ACCESS
            - resource: CVE
              access: READ_ACCESS
            - resource: Cluster
              access: READ_ACCESS
            - resource: Compliance
              access: READ_ACCESS
            - resource: Deployment
              access: READ_ACCESS
            - resource: DeploymentExtension
              access: READ_ACCESS
            - resource: Detection
              access: READ_ACCESS
            - resource: Image
              access: READ_ACCESS
            - resource: Integration
              access: NO_ACCESS
            - resource: K8sRole
              access: READ_ACCESS
            - resource: K8sRoleBinding
              access: READ_ACCESS
            - resource: K8sSubject
              access: READ_ACCESS
            - resource: Namespace
              access: READ_ACCESS
            - resource: NetworkGraph
              access: READ_ACCESS
            - resource: NetworkPolicy
              access: READ_ACCESS
            - resource: Node
              access: READ_ACCESS
            - resource: Secret
              access: READ_ACCESS
            - resource: ServiceAccount
              access: READ_ACCESS
            - resource: WatchedImage
              access: READ_WRITE_ACCESS
            - resource: VulnerabilityManagementApprovals
              access: READ_ACCESS
            - resource: VulnerabilityManagementRequests
              access: READ_WRITE_ACCESS
  data:
  - secretKey: keycloak_client_secret
    remoteRef:
      key: ACS_KEYCLOAK_CLIENT_SECRET
