apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/text
        value: hub-prod-local
      - op: replace
        path: /spec/backgroundColor
        value: "#3E8635"
    target:
      kind: ConsoleNotification
