apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- placement.yaml
- policy-service-account.yaml
- policy-clusterrole.yaml
- policy-rolebinding.yaml

generators:
- policy-generator-config.yaml
