apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - patch: |-
      - op: add
        path: /spec/argoCDAgent
        value:
          principal:
            allowedNamespaces:
              - cluster-*
            enabled: true
            image: 'quay.io/argoprojlabs/argocd-agent:v0.5.1'
            jwtAllowGenerate: true
            auth: mtls:CN=([^,]+)
      - op: add
        path: /spec/sourceNamespaces
        value: cluster-*
      - op: add
        path: /spec/controller/enabled
        value: false
      - op: remove
        path: /spec/resourceExclusions
    target:
      kind: ArgoCD
