apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml

helmCharts:
- name: external-secrets
  version: v1.3.1
  repo: https://charts.external-secrets.io
  namespace: external-secrets
  releaseName: external-secrets
  valuesFile: values.yaml
