apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: core-secrets

resources:
# These secrets need to be deployed manually, bit of chicken and egg
# - eso-token-hub-prod-local-secret.yaml
# - eso-token-workload-prod-local-secret.yaml
- namespace.yaml
- placement.yaml
- managedclusterbindingset.yaml

generators:
- policy-generator-config.yaml
