apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-lightspeed

resources:
- ns.yaml
- networkpolicy.yaml
- externalsecret.yaml
- operator-group.yaml
- subscription.yaml
- olsconfig.yaml
