apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
 name: cluster-config
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/gnunn-gitops/cluster-config-v2
        revision: main
        directories:
          - path: apps/**/overlays/all
          - path: apps/**/overlays/hub
          - path: apps/**/overlays/hub-prod
          - path: apps/**/overlays/hub-prod-local
  template:
    metadata:
      name: '{{index .path.segments 1}}'
      labels:
        name: '{{index .path.segments 1}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/gnunn-gitops/cluster-config-v2
        targetRevision: main
        path: '{{.path.path}}'
      destination:
        name: local-cluster
        namespace: '{{index .path.segments 1}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
