apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-config
  namespace: argocd-agent-hub-prod-local
  labels:
    cluster-name: hub-prod-local
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/gnunn-gitops/cluster-config-v2
        revision: main
        directories:
          - path: apps/**/overlays/all
          - path: apps/**/overlays/hub
          - path: apps/**/overlays/hub-prod
          - path: apps/**/overlays/hub-prod-local
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: name
              operator: In
              values: &core
                - external-secrets
                - cert-manager-operator

        - matchExpressions:
            - key: name
              operator: In
              values: &config
                - cert-manager
                - cluster-certs

        # - matchExpressions:
        #     - key: name
        #       operator: In
        #       values: &operators
        #         - cert-manager-issuers
        #         - cluster-certs

        - matchExpressions:
            - key: name
              operator: NotIn
              values:
                - "*core"
                - "*config"
                # - *operators

  template:
    metadata:
      name: "{{index .path.segments 1}}"
      labels:
        name: "{{index .path.segments 1}}"
        cluster-name: hub-prod-local
    spec:
      project: argocd-agent-hub-prod-local
      source:
        repoURL: https://github.com/gnunn-gitops/cluster-config-v2
        targetRevision: main
        path: "{{.path.path}}"
      destination:
        name: argocd-agent-hub-prod-local
        namespace: "{{index .path.segments 1}}"
      syncPolicy:
        automated:
          enabled: true
          selfHeal: true
          prune: false
  templatePatch: |
    {{- if or (eq (index .path.segments 1) "external-secrets") }}
    metadata:
      annotations:
        argocd.argoproj.io/compare-options: ServerSideDiff=true
    spec:
      syncPolicy:
        syncOptions:
          - ServerSideApply=true
    {{- end }}
