apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: argocd-agent-registration
placementBindingDefaults:
  name: argocd-agent-registration
policyDefaults:
  complianceType: "mustonlyhave"
  consolidateManifests: false
  namespace: acm-policies
  remediationAction: enforce
policies:
  - name: argocd-agent-registration
    description: Register Argo CD Agents on Control Plane
    manifests:
      - path: manifests
    placement:
      placementName: argocd-agent-registration
