apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: bootstrap-policy-generator
policyDefaults:
  complianceType: "mustonlyhave"
  namespace: acm-policies
  remediationAction: enforce
  generatePolicyPlacement: false
policies:
  - name: gitops-subscription
    manifests:
      - path: manifests/base/
