apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/text
        value: workload-prod-local
      - op: replace
        path: /spec/backgroundColor
        value: "#0066CC"
    target:
      kind: ConsoleNotification
