apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: bootstrap-policy-generator
policyDefaults:
  namespace: acm-policies
  remediationAction: enforce
placementBindingDefaults:
  name: "bootstrap"
policies:
  - name: eso-secret-store
    manifests:
      - path: manifests/eso-secret-store/base/
  - name: gitops-subscription
    manifests:
      - path: manifests/gitops-subscription/base/
  - name: gitops-control-plane
    configurationPolicyAnnotations:
      policy.open-cluster-management.io/disable-templates: "true"
    manifests:
      - path: manifests/gitops-control-plane/base/
policySets:
  - name: "bootstrap"
    description: "Policy for bootstrapping clusters using OpenShift GitOps"
    policies:
      - eso-secret-store
      - gitops-subscription
      - gitops-control-plane
    generatePolicySetPlacement: false
    placement:
      name: bootstrap

