apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: bootstrap-policy-generator
policyDefaults:
  complianceType: "mustonlyhave"
  namespace: acm-policies
  remediationAction: enforce
placementBindingDefaults:
  name: "gitops-subscription"
policies:
  - name: gitops-subscription
    manifests:
      - path: manifests/base/
    placement:
      placementName: gitops-subscription

