apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: csi-driver-nfs

helmCharts:
- name: csi-driver-nfs
  version: v4.13.1
  repo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
  namespace: csi-driver-nfs
  releaseName: csi-driver-nfs
  valuesFile: values.yaml
  kubeVersion: "v1.33.6"

resources:
- namespace.yaml
- scc-rolebinding.yaml
