apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-config
  labels:
    cluster-name: workload-prod-local
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/gnunn-gitops/cluster-config-v2
              revision: main
              directories:
                - path: apps/**/overlays/all
                - path: apps/**/overlays/workload
                - path: apps/**/overlays/workload-prod
                - path: apps/**/overlays/workload-prod-local
              values:
                name: "{{ index .path.segments 1 }}"
                destinationNamespace: "{{ index .path.segments 1 }}"
                serverSideApply: "false"
          - merge:
              mergeKeys:
                - name
              generators:
                - list:
                    elements:
                      - name: "{{index .path.segments 1}}"
                        destinationNamespace: "{{ index .path.segments 1 }}"
                        serverSideApply: "false"
                - list:
                    elements:
                      - name: openshift-oauth
                        destinationNamespace: openshift-config
                      - name: lvm-operator
                        destinationNamespace: openshift-storage
                      - name: external-secrets
                        serverSideApply: "true"
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: name
              operator: In
              values: &core
                - external-secrets
                - cert-manager-operator
                - lvm-operator

        - matchExpressions:
            - key: name
              operator: In
              values: &config
                - cert-manager
                - cluster-certs

        - matchExpressions:
            - key: name
              operator: NotIn
              values:
                - "*core"
                - "*config"

  template:
    metadata:
      name: "{{ .name }}"
      labels:
        name: "{{ .name }}"
        serverSideApply: "{{ .serverSideApply }}"
        cluster-name: workload-prod-local
    spec:
      project: argocd-agent-workload-prod-local
      source:
        repoURL: https://github.com/gnunn-gitops/cluster-config-v2
        targetRevision: main
        path: "{{.path.path}}"
      destination:
        name: argocd-agent-workload-prod-local
        namespace: "{{ .destinationNamespace }}"
      syncPolicy:
        automated:
          enabled: true
          selfHeal: true
          prune: false
  templatePatch: |
    {{- if eq .serverSideApply "true" }}
    metadata:
      annotations:
        argocd.argoproj.io/compare-options: ServerSideDiff=true
    spec:
      syncPolicy:
        syncOptions:
          - ServerSideApply=true
      {{- end }}
