apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/servingCerts/namedCertificates/0/names/0
        value: api.hub.ocplab.com
    target:
      kind: APIServer
      name: cluster
  - patch: |-
      - op: replace
        path: /spec/commonName
        value: "*.apps.hub.ocplab.com"
      - op: replace
        path: /spec/dnsNames/0
        value: "*.apps.hub.ocplab.com"
    target:
      kind: Certificate
      name: openshift-wildcard
  - patch: |-
      - op: replace
        path: /spec/commonName
        value: "api.hub.ocplab.com"
      - op: replace
        path: /spec/dnsNames/0
        value: "api.hub.ocplab.com"
    target:
      kind: Certificate
      name: openshift-api
