apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

components:
- ../../components/alert-rules
- ../../components/action-compliance
- ../../components/extension-assistant-lightspeed
- ../../components/oidc-keycloak-ocplab
- ../../components/agent-principal
- ../../components/plugin-ocp-config

resources:
- ../../base
