apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rhacs-operator

resources:
  - namespace.yaml
  - operatorgroup.yaml
  - subscription.yaml
  - declarative-config.yaml

# patches:
#   - patch: |-
#       - op: add
#         path: /spec/scannerV4
#         value:
#           scannerComponent: AutoSense
#           monitoring:
#             exposeEndpoint: Enabled
#     target:
#       kind: SecuredCluster
#   - patch: |-
#       - op: add
#         path: /spec/central/declarativeConfiguration
#         value:
#           secrets:
#             - name: declarative-configurations
#       - op: add
#         path: /spec/scannerV4
#         value:
#           scannerComponent: Enabled
#           monitoring:
#             exposeEndpoint: Enabled
#     target:
#       kind: Central
