apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- notifications-config.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/notifications/enabled
        value: true
    target:
      kind: ArgoCD
