apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rhacs-operator

resources:
- ../../base
- central.yaml
- admission-control-tls-push-secret.yaml
- collector-tls-push-secret.yaml
- sensor-tls-push-secret.yaml
