apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: open-cluster-management-observability

generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana-custom-dashboard: "true"

resources:
  - namespace.yaml
  - acm-observability-bucket.yaml
  - eso-push-rbac.yaml
  - eso-push-secret.yaml
  - custom-metrics-allowlist.yaml
  - multiclusterobservability.yaml

configMapGenerator:
  - name: gitops-dashboard
    files:
      - gitops.json=gitops-dashboard.json
