apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../secured-cluster

patches:
  - patch: |
      - op: replace
        path: /spec/clusterName
        value: workload-prod-local
    target:
      kind: SecuredCluster
